# Generated by Django 4.1.7 on 2023-06-26 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pr1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.DateField(default=django.utils.timezone.now)),
                ('usert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pr1.details')),
            ],
        ),
    ]
