# Generated by Django 4.1.7 on 2023-06-27 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pr1', '0002_details_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
