# Generated by Django 4.1.7 on 2023-08-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr1', '0006_apk'),
    ]

    operations = [
        migrations.AddField(
            model_name='apk',
            name='file',
            field=models.FileField(blank=True, upload_to='file'),
        ),
        migrations.AlterField(
            model_name='apk',
            name='pic',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
